#!/usr/bin/env python3
# -*- coding: utf-8 -*-

MSQ_RW_READ = 1
MSQ_RW_WRITE = 0

MSQ_CH_PROCESS = 0
MSQ_CH_PAGE = 1
MSQ_CH_DIAG = 2
MSQ_CH_ISDU = 3

MSQ_TYPE_0 = 0
MSQ_TYPE_1 = 1
MSQ_TYPE_2 = 2

ISDU_ISRV_READ_8BIT_IDX = 0b1001

ISDU_IDX_VENDOR_NAME = 0x10
ISDU_IDX_VENDOR_TEXT = 0x11
